---
- name: directory for offline pip packages
  file: path=/var/tmp/pip
        state=directory
        owner=root
        group=root
        mode=0750

- name: copy Mercurial source package from local machine
  copy: src={{ vct }}/mercurial-4.2.2+13-943c91326b23.tar.gz
        dest=/var/tmp/pip/mercurial-4.2.2+13-943c91326b23.tar.gz
        owner=root
        group=root
        mode=0640
